### ISSUE TITLE
Replace filesystem=host permission with more precise filesystem permissions

### ISSUE THREAD

**Issue by Aegeontis** [flathub/org.nicotine_plus.Nicotine#38]
As defined in the [flatpaks json](https://github.com/flathub/org.nicotine_plus.Nicotine/blob/master/org.nicotine_plus.Nicotine.json#L13), the app has full access to all system files.

I assume this is needed for users to share their music collection with the network.

Perhaps you could remove `filesystem=host` and replace it with `filesystem=home`, `filesystem=/run/media` and `filesystem=/mnt`.

While that would not be a perfect solution either (optimally flatpak would just have some kinda per folder permission portal, like Android), it would certainly be better than full access to all host files (which in theory is not necessary for nicotine)

**Comment by mathiascode** [comment]
I'd be fine with this change for now, it's highly unlikely that anyone shares system folders anyway. Ideally we would have persistent access to specific folders chosen by the user, even after system restart, but I don't think there's a solution for this right now (but let me know if I'm wrong or there are developments in the future).

**Comment by Erick555** [comment]
> Ideally we would have persistent access to specific folders chosen by the user, even after system restart, but I don't think there's a solution for this right now

This is exactly how xdg-desktop-portal work with flatpak :smile:

**Comment by mathiascode** [comment]
> > Ideally we would have persistent access to specific folders chosen by the user, even after system restart, but I don't think there's a solution for this right now
> 
> This is exactly how xdg-desktop-portal work with flatpak 😄

Yes, I know the document portal uses /run/user/1000/doc/ paths, but are they persistent? I know they exist for a while, but I'm not sure if there are cases where they are eventually cleared. We don't want a situation where at some point in the future, someone's shared folders or selected download folder suddenly isn't readable/writable anymore.

Another problem is how we would migrate existing installations where real paths are used.

**Comment by Erick555** [comment]
> Yes, I know the document portal uses /run/user/1000/doc/ paths, but are they persistent?

Yes, they are persistently stored under `~/.local/share/flatpak/db` and can be inspected from [cmdline](https://blogs.gnome.org/mclasen/2018/07/19/flatpak-a-look-behind-the-portal/)

> Another problem is how we would migrate existing installations where real paths are used.

It's not possible so IMO it's too late for changing this even as proper solution existed from the beginning.

**Comment by mathiascode** [comment]
> > Yes, I know the document portal uses /run/user/1000/doc/ paths, but are they persistent?
> 
> Yes, they are persistently stored under `~/.local/share/flatpak/db` and can be inspected from [cmdline](https://blogs.gnome.org/mclasen/2018/07/19/flatpak-a-look-behind-the-portal/)

Thanks, wish I had seen this sooner. :/

> > Another problem is how we would migrate existing installations where real paths are used.
> 
> It's not possible so IMO it's too late for changing this even as proper solution existed from the beginning.

I suppose an in-app migration step could work, but users would have to re-select their folders manually. I'll see what I can do.

**Comment by mathiascode** [comment]
Ugh, I forgot about pending/incomplete downloads, which also have destination paths set... That will be fun.

I see that support for exporting directories in the document portal was added relatively recently (2020), so it would've caused issues on older distros at the time when the Nicotine+ Flatpak was introduced. We would've ended up in this situation in any case.

I'll replace the `filesystem=host` permission with `filesystem=home` for now, with a long-term goal of removing these permissions entirely.

**Comment by julianfairfax** [comment]
The `home` permission is still quite vast. Why does it need access to the entire home folder? As far as I'm aware, it can download to or share any folder through a portal. It doesn't need constant access to a user's whole home folder? `xdg-download` should suffice?

**Comment by mathiascode** [comment]
> The `home` permission is still quite vast. Why does it need access to the entire home folder? As far as I'm aware, it can download to or share any folder through a portal. It doesn't need constant access to a user's whole home folder? `xdg-download` should suffice?

As mentioned earlier, even though we can use portals, we can't simply remove filesystem permissions without breaking every existing installation out there.
