### ISSUE TITLE
Nicotine Flatpak Cannot show East Asian Characters like Chinese, Japanese and Korean

### ISSUE THREAD

**Issue by dnet890** [flathub/org.nicotine_plus.Nicotine#47]
Hi
I use Kubuntu 22.04. But, it seems Nicotine Flatpak cannot render East Asian Character properly. Is it a bug?

https://github.com/flathub/org.nicotine_plus.Nicotine/assets/29157187/acfcac2f-68e0-42c0-b559-5727484d64a6

**Comment by slook** [comment]
Thank you for reporting the issue https://github.com/nicotine-plus/nicotine-plus/issues/2949

**Comment by mathiascode** [comment]
See https://github.com/nicotine-plus/nicotine-plus/issues/2949#issuecomment-2473554798. Not an issue in the Flatpak package itself.
